import type { Template } from "../types";

/**
 * The set of project templates the bootstrapper can scaffold.
 *
 * The `id` here must match a branch in both `scaffold_for()` and
 * `template_prereqs()` in `src-tauri/src/lib.rs`. `kinds`/`platforms` drive the
 * New Project funnel (App type → platform → framework); `scaffold` tells the UI
 * whether it's a real scaffold or a guided placeholder (opens an IDE).
 */
export const TEMPLATES: Template[] = [
  // ----------------------------- Web -------------------------------------
  {
    id: "react-vite",
    name: "React + Vite",
    description: "A lightning-fast React single-page app with TypeScript.",
    frameworks: ["React", "Vite", "TypeScript"],
    glyph: "⚛️",
    requires: "Node.js",
    accent: "from-sky-500/20 to-cyan-400/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "cli",
  },
  {
    id: "vue-vite",
    name: "Vue + Vite",
    description: "A reactive Vue 3 app with the Composition API and TypeScript.",
    frameworks: ["Vue", "Vite", "TypeScript"],
    glyph: "💚",
    requires: "Node.js",
    accent: "from-emerald-500/20 to-green-400/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "cli",
  },
  {
    id: "svelte-vite",
    name: "Svelte + Vite",
    description: "A compiled, no-virtual-DOM Svelte app with TypeScript.",
    frameworks: ["Svelte", "Vite", "TypeScript"],
    glyph: "🧡",
    requires: "Node.js",
    accent: "from-orange-500/20 to-amber-400/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "cli",
  },
  {
    id: "solid-vite",
    name: "Solid + Vite",
    description: "A fine-grained reactive UI with SolidJS and TypeScript.",
    frameworks: ["SolidJS", "Vite", "TypeScript"],
    glyph: "🔷",
    requires: "Node.js",
    accent: "from-blue-500/20 to-sky-400/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "cli",
  },
  {
    id: "preact-vite",
    name: "Preact + Vite",
    description: "A tiny 3kB React-compatible UI library with TypeScript.",
    frameworks: ["Preact", "Vite", "TypeScript"],
    glyph: "🟣",
    requires: "Node.js",
    accent: "from-fuchsia-500/20 to-purple-400/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "cli",
  },
  {
    id: "vanilla-vite",
    name: "Vanilla + Vite",
    description: "Plain TypeScript with Vite — no framework, just the basics.",
    frameworks: ["TypeScript", "Vite"],
    glyph: "🍦",
    requires: "Node.js",
    accent: "from-yellow-500/20 to-amber-300/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "cli",
  },
  {
    id: "nextjs",
    name: "Next.js",
    description: "A full-stack React framework with the App Router & Tailwind.",
    frameworks: ["Next.js", "React", "TypeScript"],
    glyph: "▲",
    requires: "Node.js",
    accent: "from-slate-400/20 to-slate-200/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "cli",
  },
  {
    id: "astro",
    name: "Astro",
    description: "A content-focused site framework that ships zero JS by default.",
    frameworks: ["Astro", "TypeScript"],
    glyph: "🚀",
    requires: "Node.js",
    accent: "from-orange-500/20 to-pink-400/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "cli",
  },
  {
    id: "angular",
    name: "Angular",
    description: "A batteries-included TypeScript app framework from Google.",
    frameworks: ["Angular", "TypeScript"],
    glyph: "🅰️",
    requires: "Node.js",
    accent: "from-red-500/20 to-rose-400/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "cli",
  },
  {
    id: "static-web",
    name: "Static Web",
    description: "A plain HTML/CSS/JS site — no build step, no dependencies.",
    frameworks: ["HTML", "CSS", "JavaScript"],
    glyph: "🌍",
    requires: "Nothing",
    accent: "from-indigo-500/20 to-purple-400/10",
    kinds: ["web"],
    platforms: ["web"],
    scaffold: "files",
  },

  // ---------------------------- Mobile -----------------------------------
  {
    id: "react-native",
    name: "React Native (Expo)",
    description: "A cross-platform mobile app scaffolded with Expo.",
    frameworks: ["React Native", "Expo"],
    glyph: "📱",
    requires: "Node.js",
    accent: "from-violet-500/20 to-fuchsia-400/10",
    kinds: ["mobile"],
    platforms: ["android", "ios", "cross"],
    scaffold: "cli",
  },
  {
    id: "flutter",
    name: "Flutter",
    description: "Google's cross-platform UI toolkit (mobile + desktop), Dart.",
    frameworks: ["Flutter", "Dart"],
    glyph: "🐦",
    requires: "Flutter SDK",
    accent: "from-sky-500/20 to-blue-400/10",
    kinds: ["mobile", "desktop"],
    platforms: ["android", "ios", "windows", "macos", "linux", "cross"],
    scaffold: "cli",
  },
  {
    id: "maui",
    name: ".NET MAUI",
    description: "C# cross-platform apps for mobile and desktop from one codebase.",
    frameworks: [".NET", "MAUI", "C#"],
    glyph: "🟪",
    requires: ".NET SDK + MAUI workload",
    accent: "from-purple-500/20 to-violet-400/10",
    kinds: ["mobile", "desktop"],
    platforms: ["android", "ios", "windows", "macos", "cross"],
    scaffold: "cli",
  },
  {
    id: "android-native",
    name: "Android (Kotlin)",
    description: "A native Android app — finish it in Android Studio.",
    frameworks: ["Android", "Kotlin"],
    glyph: "🤖",
    requires: "Android Studio",
    accent: "from-green-500/20 to-lime-400/10",
    kinds: ["mobile"],
    platforms: ["android"],
    scaffold: "placeholder",
  },
  {
    id: "ios-native",
    name: "iOS (Swift)",
    description: "A native iOS app — finish it in Xcode (Swift / SwiftUI).",
    frameworks: ["iOS", "Swift", "SwiftUI"],
    glyph: "",
    requires: "Xcode",
    accent: "from-slate-400/20 to-gray-300/10",
    kinds: ["mobile"],
    platforms: ["ios"],
    scaffold: "placeholder",
  },

  // ---------------------------- Desktop ----------------------------------
  {
    id: "tauri",
    name: "Tauri",
    description: "Tiny, fast desktop apps with a web UI and a Rust core.",
    frameworks: ["Tauri", "Rust", "Web"],
    glyph: "🦀",
    requires: "Node.js + Rust",
    accent: "from-amber-500/20 to-yellow-400/10",
    kinds: ["desktop"],
    platforms: ["windows", "macos", "linux", "cross"],
    scaffold: "cli",
  },
  {
    id: "electron",
    name: "Electron",
    description: "Cross-platform desktop apps with web tech and Node.",
    frameworks: ["Electron", "Node.js"],
    glyph: "⚛️",
    requires: "Node.js",
    accent: "from-cyan-500/20 to-teal-400/10",
    kinds: ["desktop"],
    platforms: ["windows", "macos", "linux", "cross"],
    scaffold: "cli",
  },
  {
    id: "wpf",
    name: "WPF (.NET)",
    description: "A native Windows desktop app with C# and XAML.",
    frameworks: [".NET", "WPF", "C#"],
    glyph: "🪟",
    requires: ".NET SDK",
    accent: "from-blue-500/20 to-indigo-400/10",
    kinds: ["desktop"],
    platforms: ["windows"],
    scaffold: "cli",
  },
  {
    id: "macos-native",
    name: "macOS (Swift)",
    description: "A native macOS app — finish it in Xcode (Swift / SwiftUI).",
    frameworks: ["macOS", "Swift", "SwiftUI"],
    glyph: "🍎",
    requires: "Xcode",
    accent: "from-slate-400/20 to-gray-300/10",
    kinds: ["desktop"],
    platforms: ["macos"],
    scaffold: "placeholder",
  },

  // ------------------------------ API ------------------------------------
  {
    id: "node-express",
    name: "Express (Node)",
    description: "A minimal Node.js HTTP server with an Express skeleton.",
    frameworks: ["Node.js", "Express"],
    glyph: "🟩",
    requires: "Node.js",
    accent: "from-lime-500/20 to-green-400/10",
    kinds: ["api"],
    platforms: ["cross"],
    scaffold: "files",
  },
  {
    id: "nestjs",
    name: "NestJS",
    description: "A structured, TypeScript-first Node framework for scalable APIs.",
    frameworks: ["NestJS", "Node.js", "TypeScript"],
    glyph: "🐱",
    requires: "Node.js",
    accent: "from-rose-500/20 to-red-400/10",
    kinds: ["api"],
    platforms: ["cross"],
    scaffold: "cli",
  },
  {
    id: "python-fastapi",
    name: "FastAPI (Python)",
    description: "A modern, async Python web API with automatic docs.",
    frameworks: ["Python", "FastAPI"],
    glyph: "🐍",
    requires: "Python 3",
    accent: "from-blue-500/20 to-yellow-400/10",
    kinds: ["api"],
    platforms: ["cross"],
    scaffold: "files",
  },
  {
    id: "flask",
    name: "Flask (Python)",
    description: "A lightweight Python micro-framework for small APIs.",
    frameworks: ["Python", "Flask"],
    glyph: "🍶",
    requires: "Python 3",
    accent: "from-slate-500/20 to-zinc-400/10",
    kinds: ["api"],
    platforms: ["cross"],
    scaffold: "files",
  },
  {
    id: "aspnet-core",
    name: "ASP.NET Core",
    description: "A C# web API with the .NET minimal hosting model.",
    frameworks: [".NET", "C#", "Web API"],
    glyph: "🌐",
    requires: ".NET SDK",
    accent: "from-teal-500/20 to-cyan-400/10",
    kinds: ["api"],
    platforms: ["cross"],
    scaffold: "cli",
  },
  {
    id: "go-module",
    name: "Go (net/http)",
    description: "A simple, statically-compiled Go HTTP service.",
    frameworks: ["Go"],
    glyph: "🐹",
    requires: "Go",
    accent: "from-cyan-500/20 to-sky-400/10",
    kinds: ["api", "tool"],
    platforms: ["cross"],
    scaffold: "files",
  },

  // ------------------------------ Tool -----------------------------------
  {
    id: "rust-cli",
    name: "Rust CLI",
    description: "A fast, safe command-line program built with Cargo.",
    frameworks: ["Rust", "Cargo"],
    glyph: "🦀",
    requires: "Rust",
    accent: "from-orange-600/20 to-red-400/10",
    kinds: ["tool"],
    platforms: ["cross"],
    scaffold: "cli",
  },
];

export function getTemplate(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}
